---
title: "Capitolo 2: Concetti base"
author: 
  - "Marco Chiapello"
date: '`r Sys.Date()`'
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width=9, fig.height=3.5, fig.retina=3,
  out.width = "100%",
  cache = FALSE,
  echo = FALSE,
  message = FALSE, 
  warning = FALSE,
  fig.show = TRUE,
  hiline = TRUE
)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_duo_accent(
  primary_color = "#1381B0",
  secondary_color = "#FF961C",
  inverse_header_color = "#FFFFFF",
  padding = "1px 64px 16px 64px",
  base_font_size = "30px",
  header_font_google = google_font("Josefin Slab", "600"),
  text_font_google = google_font("Roboto", "300"),
  text_slide_number_font_size = "0px",
  extra_fonts = list(
    google_font("Sofia"),
    # Young Serif by uplaod.fr
    "https://cdn.jsdelivr.net/gh/uplaod/YoungSerif/fonts/webfonts/fontface.css"
  ),
  extra_css = list(
    ".marco" = list("font-family" = "Sofia"),
    ".fl img" = list(float = "right"),
    ".fl p" = list(float = "right"),
    ".content-box" = list(
        "border-radius" = "15px",
        "overflow" = "hidden",
        "display" = "block",
        "text-align" = "center",
        "padding" = "2px",
	      "background-color" = "#FF961C",
        "margin" = "15px"),
    ".f60" = list("font-size" = "60px"),
    ".f20" = list("font-size" = "20px"),
    ".f40" = list("font-size" = "40px"),
    ".center" = list(
      margin = "auto",
      width = "50%",
      padding = "10px"),
    ".list1 p, .list1 ul li, .list1 ol li" = list(
      "line-height" = "27px",
      "font-size" = "25px",
      "margin" = "10px"),
    ".list2 p, .list1 ul li, .list1 ol li" = list(
      "line-height" = "23px",
      "font-size" = "20px",
      "margin" = "0px"),
    ".m5h4 h4" = list("margin" = "5px"),
    ".m5p p" = list("margin" = "5px")
  )
)

library(xaringanExtra)
use_tile_view() 
xaringanExtra::use_logo(
  image_url = "https://raw.githubusercontent.com/rstudio/hex-stickers/master/PNG/xaringan.png"
)
use_search(show_icon = FALSE)
use_panelset()
# TO render: rmarkdown::render('02_ConBase.Rmd', 'xaringan::moon_reader')
```

## Capitolo 2

.pull-left[

- Concetto di variabile

- Concetto di vettore

- Concetto di data.frame

- Concetto di tibble

]

---

class: center middle inverse

### Concetto di variabile

----

---

class: center middle

.f60[DEMO]

---

class: center middle inverse

### Concetto di vettore

----

---

class: center middle

.f60[DEMO]


---

class: center middle inverse

### Concetto di data.frame

----

---

class: center middle

.f60[DEMO]


---

class: center middle inverse

### Manipolazione dei dati

----

---

class: center middle

.f60[DEMO]


